version: "3"

services:
  goaly-api:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ..:/goaly-api
    depends_on:
      - cockroachdb
    command: [ "gunicorn", "--preload", "api.wsgi:app", "-w 1", "-b 0.0.0.0:8080", "-t 30" ]

  cockroachdb:
    image: cockroachdb/cockroach:v22.2.8
    ports:
      - "26257:26257"
    volumes:
      - ./cockroach-data:/cockroach/cockroach-data
    healthcheck:
      test: ["CMD", "cockroach", "node", "status", "--insecure"]
      interval: 3s
      timeout: 5s
      retries: 5
    command: start-single-node --insecure
