version: '3'

services:
  goaly-api:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ..:/goaly-api
    depends_on:
      - cockroachdb
    command: ["gunicorn", "api.wsgi:app", "-w 2", "-b 0.0.0.0:8080", "-t 30"]
  
  cockroachdb:
    image: cockroachdb/cockroach:v21.2.2
    ports:
      - "26257:26257"
    volumes:
      - ./cockroach-data:/cockroach/cockroach-data
    command: start --insecure --join=goaly-api:26257
